### PR TITLE
version: add module to store build time information

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Comment by amery** [comment]
removed unrelated commits

**Review by karasz — COMMENTED** [review]
Shouldn't this commit also contain the build system changes so the vars get populated at build time?

I am thinking here about the `-ldflags="-X ...."` entries in the `GO_BUILD_CMD`

**Comment by amery** [comment]
> Shouldn't this commit also contain the build system changes so the vars get populated at build time?
> 
> I am thinking here about the `-ldflags="-X ...."` entries in the `GO_BUILD_CMD`

the next PR adds them via .goreleaser.yml, but yes, the make build should add them too

**Comment by amery** [comment]
> Shouldn't this commit also contain the build system changes so the vars get populated at build time?
> 
> I am thinking here about the `-ldflags="-X ...."` entries in the `GO_BUILD_CMD`

change added @karasz

**Review by karasz — APPROVED** [review]
LGTM

**Pull request merged**
